### ISSUE TITLE
Wrong interceptor is chosen when multiple bindings exist

### ISSUE THREAD

**Issue by orient-man** [ninject/Ninject.Extensions.Interception#26]
Here is an example:

https://gist.github.com/orient-man/8400383

I expect result to be multiplied by 100 but the first interceptor is chosen.

**Comment by grofit** [comment]
Not sure if this is related but if I use attribute based interception and have multiple implementations for the same interface it seems to apply ones from one implementation to another.

i.e 

```
public class SomethingOne : ISomething
{
   [SayHello]
   public virtual void DoSomething();
}

public class SomethingTwo : ISomething
{
   public virtual void DoSomething();
}

Bind<ISomething>().To<SomethingOne>();
Bind<ISomething>().To<SomethingTwo>();
```

If I were to inject in a list of `ISomething` to a class, and get the `SomethingTwo` out of it and call `DoSomething` it calls the `SayHello` related interceptor, when one is not applied to that implementation.

**Comment by grofit** [comment]
Thanks guys

**Comment by grofit** [comment]
@scott-xu is this fix due to be released to nuget soon?

**Comment by scott-xu** [comment]
Released just now.
