### ISSUE TITLE
Async Interceptor, Generic Task Raises Exception before invocation of AfterInvocation

### ISSUE THREAD

**Issue by zach-snell** [ninject/Ninject.Extensions.Interception#39]
Async interceptor does not allow AfterInvocation to handle exceptions for generic Tasks prior to throwing exceptions.

In:  Ninject.Extensions.Interception/src/Ninject.Extensions.Interception/AsyncInterceptor.cs
`private void InterceptTaskWithResult<TResult>(IInvocation invocation)`

Invoking this:
`invocationClone.ReturnValue = t.Result;`

Prior to calling:
```
this.AfterInvoke(invocationClone);
this.AfterInvoke(invocationClone, t);
```

Does not allow the interceptor logic to handle the exception prior to the task throwing the AggregateExceptions.

Solution is to move AfterInvoke before assigning result:
```
this.AfterInvoke(invocationClone);
this.AfterInvoke(invocationClone, t);
invocationClone.ReturnValue = t.Result;
```

Objections?

**Comment by scott-xu** [comment]
I'd prefer "try finally" as the "AfterInvoke" should come after getting result.
