### ISSUE TITLE
Intercept class and use the logger instance of the class

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [ninject/Ninject.Extensions.Interception#55]
I've used Postsharp in my projects so far and now I want to replace it with Ninject Interception.
I would like to log the Execute method with interception and would like to use the same instance as ILogger <ExportTask>. How can I best solve that writing Interception to the same log file as ExportTask. 

public class Program
{
	public static void Main()
	{
		IKernel kernel = new StandardKernel();
		kernel.Bind(typeof(ILogger<>)).To(typeof(Logger<>));
		kernel.Bind<ExportTask>().ToSelf();
		var task = kernel.Get<ExportTask>();
		task.Execute();
	}
}

public class ExportTask
{
	
	private ILogger<ExportTask> _logger;
	
	public ExportTask(ILogger<ExportTask> logger)
	{
		_logger = logger;
	}
	
	[Intercept]
	public void Execute()
	{
		//
	}
	
}

**Comment by scott-xu** [comment]
You can check the unit test. For example: https://github.com/ninject/Ninject.Extensions.Interception/blob/master/src/Ninject.Extensions.Interception.Test/MethodInterceptionContext.cs
